# Generated by Django 4.2.7 on 2023-12-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_artist_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.album'),
        ),
    ]
